### ISSUE TITLE
Ability to specify display by GUID

### ISSUE THREAD

**Issue by dremin** [waydabber/m1ddc#10]
First off, thank you so much for this tool--it's fantastic! I'm currently using it in conjunction with Shortcuts to automate switching display inputs between my various machines.

I have three displays, and I'm finding that the display "number" changes from time to time, breaking my scripts. I noticed that when using `m1ddc display list`, each display also has a GUID, and this seems to stay consistent over time. It would be great if this GUID could be specified to `m1ddc display ...` rather than the display number to ensure consistent operation with multiple displays.

Thanks!

**Comment by waydabber** [comment]
Yes, UUID is a permanent ID generated the display. CGDirectDisplayID will change over time. When the tool was originally devised, this was not an issue since original M1 macs had a fixed ID (1 for built-in display and 2 for external - for the Mini it was 1 for USB-C/DP and 2 for HDMI). With the new MBP and now the Mac Studio this is not ok anymore.
