### ISSUE TITLE
Add this to homebrew

### ISSUE THREAD

**Issue by anonymousaga** [waydabber/m1ddc#21]
Homebrew is the package manager of the mac. It would be easier to install & update if this came via homebrew. Thanks in advance.

**Comment by waydabber** [comment]
That's a great idea! I'll be doing this, but meanwhile if somebody else wants to add the app, here's how to proceed: 

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by anonymousaga** [comment]
I can help you once i get back from vacation later this week. Thanks!

**Comment by rogerfantw** [comment]
@anonymousaga 
Do you have time to add the app to homebrew recently? I'm looking forward to installing this app via homebrew. Thanks a lot.

**Comment by anonymousaga** [comment]
Ill try after jan11 … im quite busy till then

**Comment by unlobito** [comment]
I've raised https://github.com/Homebrew/homebrew-core/pull/120078 to request m1ddc's addition to Homebrew, but I fear it may be turned down under the [stable versions](https://docs.brew.sh/Acceptable-Formulae#stable-versions) policy since this repo doesn't have tagged releases.

@waydabber Would you be able to create a tagged release for m1ddc? (e.g., `1.0` - [About Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases))

**Comment by waydabber** [comment]
@unlobito - sure, here it is!

https://github.com/waydabber/m1ddc/releases/tag/v1.0.0

**Comment by unlobito** [comment]
🚀 https://formulae.brew.sh/formula/m1ddc

**Comment by waydabber** [comment]
Nice! :)

**Comment by anonymousaga** [comment]
Im not sure what this dies cause im not getting issues, but this error came:

Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall m1ddc


When i ran that command the same error came. Thanks in advance
