### ISSUE TITLE
Won't change input on LG 32UN880-B

### ISSUE THREAD

**Issue by pierloui** [waydabber/m1ddc#6]
Hello,

I can change luminance, but when trying to switch input, the screen goes black for 1 second, and it does nothing. 

Any idea on what to do? 

Thx
Pierre-Louis

**Comment by waydabber** [comment]
Ok, that's not true, I seem to be able to change to HDMI1 or HDMI2, but no to DisplayPort. My display does not seem to use the standard values for inputs. You might want to experiment with various values for the input command. It is probably obvious by now that didn't really experiment with changing inputs that much. I will though since I want to implement this functionality into [MonitorControl](https://github.com/MonitorControl/MonitorControl).

**Comment by codexmas** [comment]
Same issue here with my LG 32UN880, tried all the input values from 1 to 30 and it just flashed to black and back to the USB-C input.

**Comment by aasmith** [comment]
Please try my patch at https://github.com/waydabber/m1ddc/pull/32. It works for my UN880, but I'd like some feedback from others as well. Note that you'll need to use the `input-alt` command.
